### ISSUE TITLE
安装运行细节

### ISSUE THREAD

**Issue by Oliver-F1** [axbug/8Char-H5#1]
作者你好，我对你写的这个软件很感兴趣，但苦于没有学习uni-app框架，不了解其搭建运行的相关知识，所以麻烦你可不可以将readme中搭建运行打包的过程写的更详细化一些？

**Comment by axbug** [comment]
你好，请将本项目克隆到本地并使用HBuilderX打开本项目（下载地址：https://www.dcloud.io/hbuilderx.html） 选择APP版本下载 使用HBuilderX打开本项目后在需要在目录内执行npm i（如果报错请检查是否安装node.js） 此命令为安装第三方依赖库 执行完毕后执行 npm run dev:h5 执行完毕后会有一个ip地址 访问即可 本项目在线访问地址：https://blog.yxbug.cn/app/8char/ 感谢你的支持和关注

**Comment by axbug** [comment]
你好，请将本项目克隆到本地并使用HBuilderX打开本项目（下载地址：https://www.dcloud.io/hbuilderx.html) 选择APP版本下载 使用HBuilderX打开本项目后在需要在目录内执行npm i（如果报错请检查是否安装node.js） 此命令为安装第三方依赖库 执行完毕后执行 npm run dev:h5 执行完毕后会有一个ip地址 访问即可 本项目在线访问地址：https://app.yxbug.cn/app/8char/ 感谢你的支持和关注

**Comment by mencomao** [comment]
app，小程序都跑不起来
